content/guides/concepts/ipns.md

Path is `/guides/concepts/dnslink` not `/concepts/dnslink`

Fix link to DNSLink on the IPNS page

---

.gitignore
Makefile

We've had lots of problems get building right because this site uses a more up-to-date version of Hugo than the rest of the IPFS sites. This attempts to fix that by just having make download and install the correct one locally.
I am *not* very good a `make`, so if other folks have better approaches, feel free to recommend changes.

Install correct version of Hugo on `make install`

---

content/guides/concepts/hashes.md

License: MIT
Signed-off-by: Pascal Precht <pascal.precht@gmail.com>

docs(guides/concepts): add concept docs for hashes

---

content/guides/concepts/dnslink.md

This PR updates `/guides/concepts/dnslink`:
-  adds a short section about "Publish via `_dnslink` subdomain"
- fixes broken link to IPNS page

docs: add section about DNSLink via Subdomain

---

content/guides/concepts/unixfs.md

The link expired in the documentation.

unixfs.md: update link to unixfs.proto

---

config.toml

This PR adds a link in the _Guides_ section, which is a first step in addressing (ha) https://github.com/ipfs/docs/issues/91. 
> ![2018-09-23--22-28-11](https://user-images.githubusercontent.com/157609/45932864-83f08880-bf83-11e8-9195-783bd441e28c.png)
See my long-term plan in https://github.com/ipfs/docs/issues/91#issuecomment-423851456

docs: link to IPFS Addressing in Web Browsers Memo

---

config.toml
content/_index.md
content/guides/examples/_index.md

This change adds links to ProtoSchool in various places with intention to improve its discoverability.
> ![2019-02-05--17-07-39](https://user-images.githubusercontent.com/157609/52286480-94206780-2968-11e9-866b-d3d0d1ee75ad.png)
cc @ipfs/docs @terichadbourne

feat: link to ProtoSchool tutorials

---

content/introduction/usage.md

This PR mentions our browser extension at the end of post-install onboarding guide.
> Supersedes https://github.com/ipfs/website/pull/182 because we moved `ipfs.io/docs` to http://docs.ipfs.io

docs(usage): mention browser extension

---

content/guides/concepts/cid.md

cid-utils is dead (https://github.com/protocol/infra/issues/382)
IPLD Explorer provides similar feature

fix: broken link to cid-utils

---

config.toml
layouts/_default/baseof.html

The internal hugo ga template in versions > v0.41 has support for doNotTrack and ga IP anonymisation, so use that instead of rolling our own.

Add doNotTrack aware google analytics

---

content/guides/examples/websites.md

As far as I can tell, we're only creating a TXT record here, and dig will never return the dnslink when asked for a TEXT record.

dig for TXT, not TEXT

---

.circleci/config.yml

- update ipfs-dns-deploy to latest so it works with cluster 0.10
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

fix: bring back deploy from ci

---

content/introduction/usage.md

This will hopefully expedite one hop in the initial installation flow starting on the ipfs.io website (which currently hits 4 separate pages before actually installing go-ipfs). Kudos to @tmcw for the suggestion here: https://macwright.org/2017/08/09/decentralize-ipfs.html

Improve first time install flow

---

Makefile

- the hugo bin is now in the node_modules, so fix the make dev task to use that.
- pull the `build` task to the top so it is the default, like our other sites.
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

fix: make `make dev` work

---

content/introduction/usage.md

The 'installing from a prebuilt package' link on https://docs.ipfs.io/introduction/usage/ takes one to https://docs.ipfs.io/introduction/install/#installing-from-a-prebuilt-package which is broken as you can observe from the response.
```
ipfs resolve -r /ipns/docs.ipfs.io/introduction/install/: no link named "install" under QmebR8zvqzuUFKKLGAjccXaJRmSkkiwYEjaUcoknpaHsX3
```
This PS fixes the broken link.

Fix broken prebuilt package installation link

---

content/guides/guides/install.md

Remove warning (we don't support building with `go get` for almost 3 years)

Update install instructions

---

content/guides/examples/websites.md

I was about to send this to someone wondering how to easily add their website to IPFS and realized it hadn't been updated recently and might no longer have the recommended path/steps for adding a website to IPFS. @aschmahmann / @hugomrdias - are the IPNS/dnslink instructions here still accurate? @olizilla - any other caveats or other instructions we should give someone trying to deploy a website to ipfs about what to do if these instructions aren't a good fit for their needs?

Update IPFS website tutorial

---

content/_index.md

Proposing this to close #216, "Basics Issues are Hard to Find."
_(Not to be confused with this [classic tale](http://xroads.virginia.edu/~drbr/goodman.html))_
Also posited in the issue was a parent / child subnav scheme, but i wonder whether that would really net us much of a usability lift.
If we added all of the subtopics to the sidenav by default, that would make the nav extremely long. But if we expanded the menu only on click, then it would essentially duplicate the list contained on the basic examples index page itself:
Neither approach seems to net us much imo, but what do you think? Having the expanded nav _would_ make it visible while users explored the various subtopics in that section. If that benefit alone is deemed a sufficient bonus, we can go ahead and add the subnav.
#216 …

Basic Examples findability

---

src/styles/components/alert.less
src/styles/components/footer.less
src/styles/components/sidebar.less
src/styles/main.less

Hairball quickfix PR that makes it so I can find links and read text on our docs pages. I was going a leeeetle crazy with the blue-on-black link situation.
Included in this PR, today only, for the low low price of three poodles and a pibble:
- Replace most type colors with brand colors from ipfs.io.
- Make links findable/readable (hopefully) (tho not accessible -- they need an indicator that *isn't* color, but this quickfix is no worse than it was)
- Sharpen alert boxes
- Smallify text in footer because it was like YELLING COPYRIGHT when you scrolled to the bottom of an article

Quick type color and alert box fixes

---

layouts/_default/baseof.html
layouts/partials/feedback.html
layouts/partials/footer.html
package-lock.json
package.json
src/js/feedback.js
src/js/main.js
src/styles/components/feedback.less
src/styles/main.less

This PR add a simple feedback mechanism to our documentation pages so we can begin to collect metrics on documents that may require attention.
__Tracked in GA as__:
+ event category: helpful/not helpful
+ event action: click
+ event label: current href
__Notes__:
+ This is a hotfix release so we can (and should) continue to improve this later on if we see usage.
+ It would be nice to also capture long-form comments as an additional dimension (we have up to 500 bytes that we can use on an events label for this)
+ We add one feedback form per page, so for the long single page documents such as the CLI and HTTP docs it won't provide a clear actionable picture.
+ This respects browser DNT settings, so if DNT is enabled no events will be collected.

feat: was this helpful?

---

config.toml
content/guides/guides/addressing.md

This PR replaces external link "Addressing in Browser" with a dedicated guide which integrates better with the rest of docs.ipfs.io and provides more elaborate introduction of each addressing scheme.
Needs proofing, aims to close #256 and act as an introduction to more technical SPEC aimed at implementers (https://github.com/ipfs/in-web-browsers/issues/147)
cc https://github.com/ipfs/in-web-browsers/issues/147,  @autonome

feat: integrate browser-addressing content

---

config.toml

Added link to basic gateway guide as found by @daviddias in https://github.com/ipfs/go-ipfs/pull/6694#discussion_r330087275 -- understood this is a bit of a temporary band-aid, as gateway topics are covered in #273, but better than not having it in current docs site at all.

Add gateway guide to nav

---

content/_index.md

I arrived at the community section of this documentation by clicking "Community" in the footer of the ipfs.io website. I actually assumed it was going to take me to a GitHub repo I've seen before (not that I enjoy that as a presentation mechanism) and wasn't expecting the docs site. 
I was trying to find links to all of the social channels (IRC, etc.) for someone who asked me where to discuss IPFS questions. When I got to the phrase "See the other links in the community section" I tried scrolling down within the page I was on but felt like I was already in the community section. The nav is so long that there was no hint of community on the portion of it in view, though it actually didn't occur to me to look there. ¯\_(ツ)_/¯ 
Is there a way to link someone to an anchor in the nav or do I …

Make it clear what "the community section" means

---

config.toml
layouts/partials/feedback.html
layouts/partials/footer.html
src/styles/components/feedback.less

Per discussion in #305 ...
- Shifted the "edit this page in GitHub" link up next to the feedback buttons
- Added "or open an issue" link at the end that references the page title in the title of the newly-created issue
Also totally accidentally pushed a change in old FAQ sidebar link to "Forum FAQ Archive". Apologies for the topical mismatch in a single PR.
Closes #305 
(since implementation of those mockups in the beta site is happening in #306)

Move "edit this page in GitHub" link to near feedback buttons per #305

---

content/guides/_index.md

Can't remove/change/rearrange last two content items on https://docs.ipfs.io/guides/ due to Hugo limitations, but can remove superfluous content and improve a callout to the install guide at the top of the page. Considering that we're deprecating the legacy docs site soon, digging into Hugo didn't seem like the best use of time. 
closes #262

Tweak guides landing page

---

layouts/partials/footer.html

Creative Commons link tag in the footer wasn't closed, so the link spilled over onto "Powered by" on the following line.

Closes link tag in footer

---

content/guides/guides/addressing.md

> Note: corresponding PR for the new docs website is at https://github.com/ipfs/ipfs-docs-v2/pull/61, but we should merge this to the old website too, just to improve SEO.
This PR adds a sample config to make it easier for people to run their own subdomain gateways before https://github.com/ipfs/go-ipfs/issues/6498 lands:
> ![Screenshot_2020-01-09 IPFS Documentation](https://user-images.githubusercontent.com/157609/72096380-63844300-331a-11ea-9d54-3238e06042b4.png)

docs: nginx config for subdomain gateway

---

content/guides/examples/_index.md

The link for js example is showing 404 on github. change it to the correct link

fixed link for js examples

---

README.md
config.toml

DO NOT MERGE UNTIL TUESDAY 28th APRIL
Adds a link to the **Recent releases** page in the docs beta to the sidebar under Go-IPFS. To be merged into `master` when the Go-IPFS 0.5 release goes live.
Since _this_ docs site is getting deprecated in ~10 days it doesn't make sense to duplicate work and add the Recent releases page to this site as well. Adding an external link should be enough.

[wip] Release/go ipfs 0.5

---

content/community/_index.md

Problem: The Markdown link syntax is backward, which means that the link takes you to https://docs.ipfs.io/community/IPFS%20Blog.
Solution: Reverse the syntax and change the URL to blog.ipfs.io, which seems to be the new blog link.

Fix blog link Markdown

---

layouts/partials/betalink.html

Similar in style to the deprecation warning on the [docs-beta.ipfs.io site](https://docs-beta.ipfs.io).
Closes ipfs/docs#501

Adds deprecation warning.

---

README.md

The Zoom ID in the IPFS community calendar is invalid. Scheduled a new Zoom meeting with a new ID. Calendar is being changed now, but still need to update here.

Quick fix for Zoom ID.

---

content/guides/concepts/dht.md

As I understand, The `m` needs to be `16` in the example of the DHT Buckets.
Please correct me if I didn't understand it correctly. I just began to go through the IPFS documentations.

Fix: The example of the DHT Buckets
