config.toml
=> Update awesome-ipfs link to live site

content/guides/concepts/cid.md
=> typo identifer -> identifier

README.md, config.toml
Hello,
This is my first contribution to the IPFS documentation, so better start small :smile:
1. I noticed a few links were dead in the menu, I fixed them
2. I also noticed there was no link to the ipfs/docs repo, I added it for convenience
I hope this contribution will be accepted, it's rather simple but remarks and constructive comments are always welcome!
=> Fix dead links and menu entries

content/guides/examples/blocks.md
=> Fix unixfs link blocks.md

.circleci/config.yml, Makefile, README.md, ci/Jenkinsfile, package-lock.json, package.json
see: https://github.com/ipfs-shipyard/ipfs-dns-deploy
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>
=> chore: move deploy to circleci

content/guides/examples/websites.md
I was using these directions to publish a static site at a domain, and wanted to update them:
* Break up into sections 
* Add more documentation on how to set up DNS records
* Clean up language
I followed the documentation in https://docs.ipfs.io/guides/concepts/dnslink/ while writing this.
=> Changes to websites.md

content/reference/js/overview.md
=> Change js-ipfs-api to js-ipfs-http-client

layouts/partials/footer.html
=> Add “Edit this page in GitHub” links

content/reference/api/http.md
I fixed a bug that resulted in some endpoints missing from docs.
=> Update API docs for 0.4.20

content/introduction/usage.md
This link has a `src` property instead of `href`.
=> Fix link to Desktop application

content/reference/api/http.md
There are some issues:
```diff
-```text
+```json
{
-    "ID": "<string>"
-    "Type": "<int>"
-    "Responses": [
-        {
-            "ID": "<string>"
-            "Addrs": [
-                "<multiaddr-string>"
-            ]
-        }
-    ]
-    "Extra": "<string>"
+  "Extra": "<string>",
+  "ID": "<peer-id>",
+  "Responses": [
+    "<object>"
+  ],
+  "Type": "<int>"
}
````
=> Update  docs for 0.4.21. Some issues.

README.md
Add link to new YouTube playlist
=> Add link to YouTube playlist

content/guides/examples/websites.md
Follow-up from PR #211, in which I italicized some text and Hugo didn't like that.
=> Update websites.md - Fixing italics that Hugo just displays as asterisks

content/reference/go/overview.md
Fix https://github.com/ipfs/docs/issues/226.
Ref https://github.com/ipfs/ipfs-cluster-website/issues/93.
=> Delete basic usage page text

config.toml, content/reference/api/libraries.md
Fix https://github.com/ipfs/docs/issues/224.
Ref https://github.com/ipfs/ipfs-cluster-website/issues/93.
=> Change the title of the JS and Go Libraries Page

content/community/contribute/how_to_help.md
=> Contributing to design rewrite

README.md
Removing Diogo, who's moved to a new project. 😥
=> Update team listing

content/community/irc.md, content/guides/guides/install.md
ref https://github.com/ipfs/website/issues/339
Searched docs repo code for "darwin", "mac", "osx" and "os x" and standardized to "macOS" accordingly.
=> Fix macos consistency

content/guides/examples/api/service/readme.md
ref https://github.com/ipfs/docs/issues/300#issuecomment-545188846
=> Removed "Making Your Own IPFS Service" from left nav

layouts/partials/feedback.html
=> Updated "open an issue link" to use new issue template from #272

content/community/_index.md
See https://github.com/ipfs/website/issues/307 -- this is half the work in that issue.
=> Fleshing out community landing page to address /website/issues/307

config.toml
=> Adds sidebar nav link to go-ipfs library tutorial

content/guides/concepts/dht.md
Thanks @bertrandfalguere!
ref #240 
closes #111
=> Copy edits on @bertrandfalguiere's new DHT concept doc

config.toml
=> Added IPFS Camp core course content to nav

content/guides/concepts/cid.md
=> Be more precise when talking of crypto primatives

content/guides/concepts/cid.md
Mulitbase is not a final specification
Source: https://github.com/multiformats/multibase#multibase-wip
So reference to it should acknowledge this.
=> Clarify multibase is WIP

content/guides/concepts/cid.md
The core bases are stable and used extensively. I've updated the README (https://github.com/multiformats/multibase) to remove the WIP marker and added stabilization statuses to each of encodings.
=> chore(concepts/cid): multibase is probably the least WIP project that we have

content/guides/guides/install.md
Explain how to enable go modules and configure PATH variable to pick up the installed binaries.
I took used content from https://github.com/ipfs/ipfs-update#from-source, see also the discussion in https://github.com/ipfs/ipfs-update/issues/113.
/cc @Stebalien
=> Update `ipfs-update` install instructions

content/guides/examples/pinning.md
=> Fixed apostrophes in pinning.md

content/introduction/usage.md
I screwed up in the last commit, so here is a fix :-)
=> Remove accidental "2" from text

content/introduction/overview.md
=> Simplified introduction paragraph. Issue #426.

content/guides/examples/bootstrap.md, content/guides/examples/network.md
=> Update example to use new bootstrap nodes

README.md
Changed sync meeting to bi-weekly, and added a time-table. Meetings run up until the end of Q1.
=> Updated time-table for sync meeting.

README.md
Looks like this wasn't updated in Jan.
=> Updated OKR link.

README.md
Updated the meeting information to reflect the new time-table.
=> Update meeting information and schedule.

README.md
Also fixed the Unix time, because we're all nerds at heart.
=> Change Monday to Tuesday.

README.md, layouts/partials/betalink.html
Changes deprecation date, adds notice to readme.
=> Deprecation notices.
